### ISSUE TITLE
Thank you! 

### ISSUE THREAD

**Issue by georgedoescode** [Stanko/offset-polygon#1]
Hey, I hope you don't mind me opening an issue here (I wasn't sure how else to contact you) 

Just wanted to say thanks for publishing such a small, effective package for polygon offsetting in JS - I've tried a few and they are usually HUGE, or don't work _quite_ how I want them to. 

Cheers :)

**Comment by Stanko** [comment]
Hehe of course I don't mind, you made my day, thank you :) 

I had the exactly same problem and once I found [Hans' CodePen](https://codepen.io/HansMuller/pen/lDfzt) I thought - finally. I made a few changes and decided to release it on npm. I hope Hans won't mind 🙈

**Comment by georgedoescode** [comment]
Ah! I'm glad to hear it! ❤️

**Comment by Stanko** [comment]
@georgedoescode I wasn't sure how to contact you either 🙈 so I sent you a linkedin request.

In other news, I found this library https://github.com/xaviergonz/js-angusj-clipper (a js clone of C clipper) which is amazing! It does all boolean operations and polygon offsetting. Documentation is a little bit hard to navigate, but the library is really good (and fast).
